services:

  postgres:
    image: postgres:16
    container_name: bus-delay-postgres

    environment:
      POSTGRES_DB: bus_delay
      POSTGRES_USER: bus_admin
      POSTGRES_PASSWORD: buspassword

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: